"""empty message

Revision ID: 09ef3a35be1a
Revises: 3735c20fec61
Create Date: 2025-03-05 14:54:13.880584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ef3a35be1a'
down_revision = '3735c20fec61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), server_default='', nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
