"""empty message

Revision ID: 20b8425e900e
Revises: 37a96171c37c
Create Date: 2025-03-01 22:28:04.295320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b8425e900e'
down_revision = '37a96171c37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
