"""empty message

Revision ID: 37a96171c37c
Revises: 8f5167ac7dd1
Create Date: 2025-02-27 15:14:02.820751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a96171c37c'
down_revision = '8f5167ac7dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_customer')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_proof', sa.String(length=12), server_default='', nullable=False))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('id_proof')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), nullable=False))

    op.create_table('_alembic_tmp_customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_customer'),
    sa.UniqueConstraint('email', name='uq_customer_email'),
    sa.UniqueConstraint('phone', name='uq_customer_phone')
    )
    # ### end Alembic commands ###
