"""empty message

Revision ID: 48a93c530402
Revises: 09ef3a35be1a
Create Date: 2025-03-07 16:15:38.127168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a93c530402'
down_revision = '09ef3a35be1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_agent_id', sa.Integer(), nullable=False),
    sa.Column('base_pay', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('trips_count', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agent.id'], name=op.f('fk_earnings_delivery_agent_id_delivery_agent')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_earnings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings')
    # ### end Alembic commands ###
