"""Remove address column from customer

Revision ID: 702c4be2fdb5
Revises: c39db9536484
Create Date: 2025-02-27 00:08:30.567791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702c4be2fdb5'
down_revision = 'c39db9536484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
