"""empty message

Revision ID: 823fc04dc31c
Revises: 1d7363a01e70
Create Date: 2025-03-09 18:15:23.183293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823fc04dc31c'
down_revision = '1d7363a01e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_agent_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agent.id'], name=op.f('fk_delivery_feedback_delivery_agent_id_delivery_agent')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_delivery_feedback_order_id_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_feedback'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_feedback')
    # ### end Alembic commands ###
