"""empty message

Revision ID: b534cae373b2
Revises: 
Create Date: 2025-03-19 17:53:11.838342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b534cae373b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('pk_admin')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_admin_phone'))
    )
    op.create_table('categories',
    sa.Column('category_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories'))
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customer')),
    sa.UniqueConstraint('email', name=op.f('uq_customer_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_customer_phone'))
    )
    op.create_table('delivery_agent',
    sa.Column('delivery_agent_id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), server_default='', nullable=True),
    sa.Column('bio', sa.Text(), server_default='', nullable=True),
    sa.Column('delivery_area', sa.String(length=100), nullable=False),
    sa.Column('available_slots', sa.Boolean(), nullable=False),
    sa.Column('id_proof', sa.String(length=12), server_default='', nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('delivery_agent_id', name=op.f('pk_delivery_agent')),
    sa.UniqueConstraint('email', name=op.f('uq_delivery_agent_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_delivery_agent_phone'))
    )
    op.create_table('address',
    sa.Column('address_id', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_address_customer_id_customer')),
    sa.PrimaryKeyConstraint('address_id', name=op.f('pk_address'))
    )
    op.create_table('earnings',
    sa.Column('earnings_id', sa.String(length=10), nullable=False),
    sa.Column('delivery_agent_id', sa.String(length=10), nullable=False),
    sa.Column('base_pay', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('trips_count', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agent.delivery_agent_id'], name=op.f('fk_earnings_delivery_agent_id_delivery_agent')),
    sa.PrimaryKeyConstraint('earnings_id', name=op.f('pk_earnings'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('delivery_agent_id', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Preparing', 'Out for Delivery', 'Delivered', 'Cancelled', name='order_status'), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('delivery_location', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_orders_customer_id_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agent.delivery_agent_id'], name=op.f('fk_orders_delivery_agent_id_delivery_agent'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    op.create_table('subcategories',
    sa.Column('subcategory_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_subcategories_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subcategory_id', name=op.f('pk_subcategories'))
    )
    op.create_table('delivery_feedback',
    sa.Column('delivery_feedback_id', sa.String(length=10), nullable=False),
    sa.Column('order_id', sa.String(length=10), nullable=False),
    sa.Column('delivery_agent_id', sa.String(length=10), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agent.delivery_agent_id'], name=op.f('fk_delivery_feedback_delivery_agent_id_delivery_agent')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_delivery_feedback_order_id_orders')),
    sa.PrimaryKeyConstraint('delivery_feedback_id', name=op.f('pk_delivery_feedback'))
    )
    op.create_table('menu_items',
    sa.Column('menu_item_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('category_id', sa.String(length=10), nullable=False),
    sa.Column('subcategory_id', sa.String(length=10), nullable=False),
    sa.Column('nutrient_value', sa.String(length=255), nullable=False),
    sa.Column('calorie_count', sa.Integer(), nullable=False),
    sa.Column('is_best_seller', sa.Boolean(), nullable=True),
    sa.Column('is_out_of_stock', sa.Boolean(), nullable=True),
    sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('stock_available', sa.Integer(), nullable=True),
    sa.Column('scheduled_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_menu_items_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.subcategory_id'], name=op.f('fk_menu_items_subcategory_id_subcategories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', name=op.f('pk_menu_items')),
    sa.UniqueConstraint('name', name=op.f('uq_menu_items_name'))
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('menu_item_id', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_cart_customer_id_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], name=op.f('fk_cart_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', name=op.f('pk_cart'))
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.String(length=10), nullable=False),
    sa.Column('order_id', sa.String(length=10), nullable=False),
    sa.Column('menu_item_id', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], name=op.f('fk_order_item_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_order_item_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id', name=op.f('pk_order_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('cart')
    op.drop_table('menu_items')
    op.drop_table('delivery_feedback')
    op.drop_table('subcategories')
    op.drop_table('orders')
    op.drop_table('earnings')
    op.drop_table('address')
    op.drop_table('delivery_agent')
    op.drop_table('customer')
    op.drop_table('categories')
    op.drop_table('admin')
    # ### end Alembic commands ###
