"""Added Address table and changed phone to String

Revision ID: cfebceff51d7
Revises: 749052536525
Create Date: 2025-02-26 23:18:02.975831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfebceff51d7'
down_revision = '749052536525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_proof', sa.String(length=12), nullable=False))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agent', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('id_proof')

    # ### end Alembic commands ###
